name: Build and Test MetromontCastLink

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '9.0.x'
  SOLUTION_PATH: './MetromontCastLink.sln'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Setup .NET 8.0 (for Shared project)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
    
    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Release
    
    - name: Test
      run: dotnet test ${{ env.SOLUTION_PATH }} --no-build --configuration Release --verbosity normal
    
    - name: Publish
      run: dotnet publish ./MetromontCastLink/MetromontCastLink/MetromontCastLink.csproj -c Release -o ./publish
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: metromont-castlink
        path: ./publish
        retention-days: 5
         
